### ISSUE TITLE
Spaces, not tabs

### ISSUE THREAD

**Issue by huyz** [obsidianmd/obsidian-sample-plugin#34]
Very questionable choice to default to tabs in `.editorconfig`.  Take a look all over Github; you almost never see tabs (no arrows when looking at source code on github.com).

Now, lots of Obsidian plugins have tabs which just serves to annoy everyone who wants to contribute PRs.

**Comment by lishid** [comment]
I like tabs. If using tabs is questionable then there wouldn't be an option for anyway.

Most people just follow whatever standards a project already uses, and `.editorconfig` serves exactly that purpose so that tools like IDEs can automatically follow whatever the project uses.

github.com never display arrows for tabs:
![image](https://user-images.githubusercontent.com/609710/181451818-55bacc93-bab1-4f43-a7b9-9205088f1f06.png)

**Comment by huyz** [comment]
You're right, it's not that github.com that added arrows.  It's my https://github.com/refined-github/refined-github extension.  

Fair enough about your preference. Just be aware that this is not a popular choice for JavaScript/TypeScript: https://ukupat.github.io/tabs-or-spaces/

**Comment by lishid** [comment]
Hey, 16.78% is a good enough size (plus that's a really low sample size). Either way, this isn't a popularity contest and in the vast majority of the cases this choice doesn't really matter.

![](https://www.emacswiki.org/pics/static/TabsSpacesBoth.png)

**Comment by lishid** [comment]
One could also argue that Tabs is best used in this kind of templates because it gives everyone a visual choice of whether to use 2 spaces for each tab or 4 spaces for each tab, without constantly converting the source code itself between the two.

Either way, this is likely one of the top unsolved problems in the computing world along with Windows vs Mac vs Linux.



> (Some in fact may call it a [career/financial consideration](https://www.7pace.com/blog/programming-spaces-vs-tabs) lol. J/k)

In that case, we should probably make plugins [in Closure instead](https://insights.stackoverflow.com/survey/2019#top-paying-technologies).
